# Etapa 1: Construcción del JAR
FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /app

# Copiar archivos del proyecto
COPY pom.xml .
COPY src ./src

# Compilar sin ejecutar tests
RUN mvn clean package -DskipTests

# Etapa 2: Imagen final con el JAR listo
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app

# Copiar el .jar generado desde la etapa anterior
COPY --from=build /app/target/*.jar app.jar

# Exponer el puerto del backend
EXPOSE 8080

# Variables de entorno por defecto (puedes sobreescribirlas al ejecutar)
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5433/tools_rent
ENV SPRING_DATASOURCE_USERNAME=postgres
ENV SPRING_DATASOURCE_PASSWORD=admin

# Comando de inicio
ENTRYPOINT ["java", "-jar", "app.jar"]
