pipeline {
    agent any

    environment {
        DOCKER_HUB_USER = 'tm4ra'               
        IMAGE_NAME      = 'toolrent-backend'    
        IMAGE_TAG       = "build-${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                
                checkout scm
            }
        }

        stage('Build & Test (Maven)') {
            steps {
                dir('Backend') {                 
                    sh 'chmod +x mvnw'         
                    sh './mvnw clean test'
                    sh './mvnw package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                  docker build \
                    -t ${DOCKER_HUB_USER}/${IMAGE_NAME}:${IMAGE_TAG} \
                    -f Backend/dockerfile Backend

                  docker tag ${DOCKER_HUB_USER}/${IMAGE_NAME}:${IMAGE_TAG} \
                             ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest
                """
            }
        }

        stage('Login & Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-creds',  
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                      docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:${IMAGE_TAG}
                      docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest
                    """
                }
            }
        }
    }

    post {
        always {
            sh 'docker system prune -f || true'
        }
    }
}
